name: Runtest

on: 
  [push]
  
jobs:
  Tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
         
          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.18
          
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: test
        env: 
          DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/TodoBuffalo_test?sslmode=disable"
        run: |
          go install github.com/wawandco/ox/cmd/ox@0.12.3
          ox test
          
      
