name: Runtest

on:
  [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download ox
        run : |
          go install github.com/wawandco/ox/cmd/ox@latest
      - name: generate cmd ox
        run : |
          ox generate ox
      - name: Run test
        run: |
          ox test
     