name: Runtest

on: 
  [push]
  
jobs:
  Tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/TodoBuffalo_test?sslmode=disable
          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.18
          
      - name: installOX
        run : |
          go install github.com/wawandco/ox/cmd/ox@latest
    
      - name: runTest
        run : |
          ox test
          
      
